name: Task3_Java_maven

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-java@v3
       with:
        java-version: '11'
        distribution: 'adopt'
     - run: mvn -B package --file pom.xml
     - run: mkdir staging && cp target/*.jar staging
     - uses: actions/upload-artifact@v3
       with:
        name: Package
        path: staging
